name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          sudo apt install texlive-pstricks texlive-latex-extra texlive-science
          awk '!/PDF/' /etc/ImageMagick-6/policy.xml > temp && sudo mv temp /etc/ImageMagick-6/policy.xml
          for texfile in $(ls | grep '\.tex'); do 
            fname="${texfile%.tex}";
            latex "$fname.tex";
            dvips "$fname.dvi";
            ps2pdf "$fname.ps";
            convert -density 300 "$fname.pdf" "$fname.png";
          done
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          path: '*.png'
