name: Build
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@97bae119d017e25bfb37ce8e5d95b1d64135f00b
        with:
          root_file: '*.tex'
          glob_root_file: true
          working_directory: '.'
          compiler: latexmk
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          extra_system_packages: 'texmf-dist-pstricks libwmf'
          post_compile: 'apk add convert && convert -density 300 output.pdf myImage.png'
          latexmk_use_xelatex: true
