name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          sudo apt install texlive-pstricks texlive-latex-extra texlive-science
          latex main.tex
          dvips main.dvi
          ps2pdf main.ps
          awk '!/PDF/' /etc/ImageMagick-6/policy.xml > temp && sudo mv temp /etc/ImageMagick-6/policy.xml
          convert -density 300 main.pdf myImage.png
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          path: '*.png'
